fix: Improve type prefix and suffix extraction
akhundMurad/typeid-python pull request #13
Opened 2024-05-13 19:02 UTC by iron3oxide

Refactored the logic in `get_prefix_and_suffix` function to improve type prefix and suffix extraction. Now using `rsplit` method to accurately extract the prefix and suffix from the input string. 

Closes #12

2024-05-14 12:36 UTC, akhundMurad commented
Hello @iron3oxide 
Your changes broke the TypeID spec validation.
Please try to resolve them and add additional tests to your case.
Thanks for your contribution!

2024-05-14 13:18 UTC, iron3oxide commented
Done! My pleasure

2024-05-18 21:46 UTC, khasizadaj requested changes

2024-05-18 21:46 UTC, khasizadaj commented on typeid/typeid.py
> +        prefix, suffix = parts
This doesn't work as it should. As you can see from the exception raised in the test,  it is not `InvalidTypeIDStringException` but `SuffixValidationException`.

It fails when you provide a string with multiple underscores. In that case `part[0]` will never be equal to an empty string and the prefix will be incorrect, in other words, we won't be able to throw an error. 

Better to use `split` and add another condition for length being 3 or more. 

```suggestion
    elif len(parts) >= 3:
        raise InvalidTypeIDStringException(f"Invalid TypeID: {string}")
    else:
        prefix, suffix = parts
```

2024-05-18 21:46 UTC, khasizadaj commented on typeid/typeid.py
> +    parts = string.rsplit("_", 1)
I am suggesting this because of the next comment.

```suggestion
    parts = string.split("_")
```

2024-05-18 23:20 UTC, iron3oxide commented
@khasizadaj I am replying here because it is easier to follow the conversation this way. I don't quite understand your suggested changes.

To preface this: In my opinion, `get_prefix_and_suffix()` should aim to do just that: extract the prefix and suffix candidates from the given string. A special case where it is preferable to raise an error early is a single leading underscore in the given string. 

After that it is up to the `TypeID` class to correctly flag the given prefix and suffix as invalid; which it does, as the tested string in the test you mentioned contains a valid prefix according to the TypeID spec, but no valid suffix. A string such as "___test_invalid_00041061050r3gg28a1c60t3gf" is also correctly flagged as containing an invalid prefix. Could you give me an example string where the changes suggested in this PR produce an unexpected or wrong outcome?

2024-05-19 11:52 UTC, khasizadaj commented
Thanks for the clarification. I was thinking that it could be useful to throw exception before that as well, but now I understand your POV as well. We can disregard my comment.

2024-05-19 14:54 UTC, akhundMurad commented
@iron3oxide @khasizadaj 
may I resolve the conversation above?

2024-05-19 15:01 UTC, iron3oxide commented
Yes, I think it's ready to be merged

2024-05-19 15:04 UTC, akhundMurad commented
@iron3oxide @khasizadaj 
thanks, guys!
I will include it in the next release.

2024-05-19 15:04 UTC, khasizadaj commented
Yes, it can be closed! Thanks a lot, @iron3oxide.

2024-06-16 13:12 UTC, akhundMurad approved these changes

2024-06-16 13:12 UTC, merged